# Generated by Django 6.0 on 2025-12-18 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username_normalized', models.TextField(unique=True)),
                ('username_display', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('current_rating_blitz', models.IntegerField(blank=True, null=True)),
                ('current_rating_rapid', models.IntegerField(blank=True, null=True)),
                ('current_rating_bullet', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_game_time', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('opponent_username', models.TextField(blank=True, null=True)),
                ('opponent_rating', models.IntegerField(blank=True, null=True)),
                ('played_as_color', models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], max_length=5, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('rating_after_game', models.IntegerField(blank=True, null=True)),
                ('time_class', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('pgn', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(db_column='player_username', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tracker.player', to_field='username_normalized')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
