# Generated by Django 6.0 on 2026-04-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_games_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
