# Generated by Django 6.0 on 2026-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_player_last_games_sync_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player', '-end_time'], name='games_player_end_idx'),
        ),
    ]
