# Generated by Django 6.0 on 2026-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_game_games_player_end_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_profile_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
